#-------------------------------
# General Site Settings

menu:
- {name: 'About',    url: 'about'}
- {name: 'Projects', url: ''}
- {name: 'Blog',     url: 'https://studyanddebug.tistory.com/'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: '유아용품 데이터 분석',   url: 'proj-1'}
- {name: '환편기 예지 보전',   url: 'proj-2'}
- {name: 'P-GPT 로그 분석', url: 'proj-3'}
# - {name: 'Project Four',  url: 'proj-4'}

#-------------------------------
# Contact Section

social:
- {icon: 'instagram', link: 'https://instagram.com/'}
- {icon: 'github',    link: 'https://github.com/Utaewook'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
